test:
  workers:
    type: local
    number: 1
  rounds:
    - label: Round 1/query 1000 bidding messages at 50 TPS to the blockchain  #Query all chits/ Read multiple transactions. 
      #txDuration: 30 #transaction duration - the transaction run 30 seconds
      txNumber: 1000  # Set the total number of transactions we want to execure/total number of transaction in this round round
      rateControl:
          type: fixed-load
          opts:
            tps: 50 #100 #with  of 5 TPS- per second number of transaction
            #transactionLoad: 5  # new
      workload:
        module: benchmarks/scenario/simple/chitfund/queryChit.js       #queryAllChits.js  #createChit.js   #queryAllChits.js                  
        #module: benchmarks/scenario/simple/fabcar/changeOwner.js
        # arguments:
        #   # - '-c'
        #   # - '4000'
        #   assets: 10  # previously its 10 in all need in read operation queryAllChits.js not in write operation createChit.js
        #   startKey: '1'
        #   endKey: '250' #'100'  #'50'
    - label: Round 2/query 1000 bidding messages at 100 TPS to the blockchain #Query a chit/ Read single transaction.
      #txDuration: 10
      #txDuration: 30     #new
      txNumber: 1000
      rateControl:
          type: fixed-load
          opts:
            tps: 100 #100  #new
            # transactionLoad: 5
      workload:
        module: benchmarks/scenario/simple/chitfund/queryChit.js    #queryAllChits.js    #queryChit.js  #createChit.js #queryAllChits.js #createChit.js                       #
        #arguments:
          #assets: 10
          #startKey: '1'
          #endKey: '50'
    - label: Round 3/query 1000 bidding messages at 150 TPS to the blockchain #Create a chit/ Write.
      #txDuration: 30
      txNumber: 1000
      rateControl:
          type: fixed-load
          opts:
            tps: 150  #100 #new
            # transactionLoad: 5
      workload:
        module: benchmarks/scenario/simple/chitfund/queryChit.js       #queryAllChits.js   #queryChit.js  #createChit.js  #queryAllChits.js #createChit.js                       
        # arguments:
        #   assets: 10
        #   startKey: '1'
        #   endKey: '50'
    - label: Round 4/query 1000 bidding messages at 200 TPS to the blockchain #Create a chit/ Write.
      #txDuration: 30
      txNumber: 1000
      rateControl:
          type: fixed-load
          opts:
            tps: 200  #new
            #transactionLoad: 5
      workload:
        module: benchmarks/scenario/simple/chitfund/queryChit.js       #queryAllChits.js         #queryChit.js  #queryAllChits.js #createChit.js                       #createChit.js
        #arguments:
          #assets: 10
          #startKey: '1'
          #endKey: '50'
    - label: Round 5/query 1000 bidding messages at 250 TPS to the blockchain #250 TPS #Create a chit/ Write.
      #txDuration: 30
      txNumber: 1000
      rateControl:
          type: fixed-load
          opts:
            tps: 250 #100  #new
            #transactionLoad: 5
      workload:
        module: benchmarks/scenario/simple/chitfund/queryChit.js         #queryAllChits.js      #queryChit.js #queryAllChits.js #createChit.js     
        #arguments:
          #assets: 10
          #startKey: '1'
          #endKey: '50' 
    - label: Round 6/query 1000 bidding messages at 300 TPS to the blockchain #250 TPS #Create a chit/ Write.
      #txDuration: 30
      txNumber: 1000
      rateControl:
          type: fixed-load
          opts:
            tps: 300 #100  #new
            #transactionLoad: 5
      workload:
        module: benchmarks/scenario/simple/chitfund/queryChit.js         #queryAllChits.js      #queryChit.js  #queryAllChits.js #createChit.js     
        #arguments:
          #assets: 10
          #startKey: '1'
          #endKey: '50' 
    #- label: Round 7/Query 350 messages at 25 TPS #250 TPS #Create a chit/ Write.
      ##txDuration: 30
      #txNumber: 350
      #rateControl:
          #type: fixed-load
          #opts:
            #tps: 25 #100  #new
            ##transactionLoad: 5
      #workload:
        #module: benchmarks/scenario/simple/chitfund/queryChit.js  #queryAllChits.js #createChit.js     
        #arguments:
          #assets: 10
          #startKey: '1'
          #endKey: '50' 
    #- label: Round 8/Query 400 messages at 25 TPS #250 TPS #Create a chit/ Write.
      ##txDuration: 30
      #txNumber: 400
      #rateControl:
          #type: fixed-load
          #opts:
            #tps: 25 #100  #new
            ##transactionLoad: 5
      #workload:
        #module: benchmarks/scenario/simple/chitfund/queryChit.js #queryAllChits.js #createChit.js     
        #arguments:
          #assets: 10
          #startKey: '1'
          #endKey: '50'                            
monitors:
  resource:
  - module: docker
    options:
      interval: 5 #5 # declares the monitoring of all local docker containers, with a 50 second update frequency. To solve error cpu_usage increse the interval value 10,20,30,....
      containers: #[all]
      - all
    charting:   # 1 tab right all contains
      bar:
        metrics: [Memory(max), CPU%(avg)]
        #metrics: [all]
        #metrics: [CPU%(avg), Memory(max)]
      polar:
        metrics: [all]
  - module: process
    options:
      interval: 3
      processes: [{ command: 'node', arguments: 'caliper', multiOutput: 'avg' }]
    charting: # 1 tab right all contains
      bar:
        metrics: [all]
