name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  # command:
  #   start: export FABRIC_VERSION=1.4.4;export FABRIC_CA_VERSION=1.4.4;docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml up -d;sleep 10s
  #   end: docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

info:
  Version: 2.2.4
  Size: 2 Orgs with 2 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/2b4b105355d358cb681366e0b06a59f0829f1c9f4ae91a22a95876941c391394_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/445906f0a44e3611836a74ddd6051fdb04550a97db2da63223c70dbfb3aecfa2_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/a7fceebd14033eccc84dd84e169369352dddfc9cc0607cd052bdf15cdca02b0b_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/4dc58cbe1e8adb5bc62326acc6b105829d38caf8fe663be0746def12d79a2329_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/2e2c640ef58b0dd98645c64ac690774a023a323e73d3db3d4ea412ccdc1b914f_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/5f1cdba26fb3c89341f48d7466a47b7837d66d36a427264820497b678b8dae71_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/7ce5275b546775c48cc395e2bdc6da3f577b332502364363e47ebc60eb9164d7_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/16b74f5f3f720d2c3e69e9b4271d53faf31baaca4ccd3b3abdf935e8e48c90a2_sk
        # 2 org and 4 peers
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/2113fd468504f0f0fd3a1f2f3aa4cca8f2a14898e8ac1fb48c299a365f40d3d8_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/59a419eccd00244aa35a3595a9d5f2a7dbcca707e436809c8436f2977181c52a_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/17cd98d76b901bfd0cde2fe85cc8183eaf0452c2f6a540d1eed4ffe34683b697_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/2ec30e23a83ec26347f20ea2a375c974cd9a649d70ea05185b298f4e81adbea8_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/4b254ed930c660a1c1f05074816e7b3f712ce2892e76f987e0e9c8265adea6c9_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/9b819e95971c8a4eb29f506d64f167d33aa4a1780519051b15138f695a310ac8_sk
        # 2 org and 2 peers
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/d1451e8068abfa856f72e2db72a0ec684722fa6bd05d6edc45f65a6cdaeb2a5b_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/990f6668e167a6810dbcd28c06106dc1da9ac77d7e74f57c2dd630818d10520a_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/1d566672708e38bff9139ed0915a730370af9b3365026e2e2c293fddff0c518d_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/2214b738188a49242f6f8e4fd994ff958103b26eb3f9eb453e21fcf1b6b5f464_sk
        path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/3900faf92027f675e3607afc2c5daab7474c6378621891cc21d191cedb2248ba_sk
      clientSignedCert:
        path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem

  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/2b4b105355d358cb681366e0b06a59f0829f1c9f4ae91a22a95876941c391394_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/445906f0a44e3611836a74ddd6051fdb04550a97db2da63223c70dbfb3aecfa2_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/a7fceebd14033eccc84dd84e169369352dddfc9cc0607cd052bdf15cdca02b0b_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/4dc58cbe1e8adb5bc62326acc6b105829d38caf8fe663be0746def12d79a2329_sk
        #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/2e2c640ef58b0dd98645c64ac690774a023a323e73d3db3d4ea412ccdc1b914f_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/be48f81c7fa53bb5f7e3c328c82a2fc1a9ac2c1e72a14b053e370555d1248e89_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/d75aa3be328abc82fd47332b4da6753ebe40d02d5d17012d7136b1391d234660_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/1d03734ad158c17e46c0f694b44aa4f7073f05b8a70e6a100bf52b5e57c86456_sk
        # 2 org 4 peers
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/828d7a69a51e24ce5c770b6d98edc34fa94604127d942536b4a76020f7b7e043_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/74ac7032352acb82e32ede000736a37807d9a544ce3960bbacae87a1e631a242_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/5d8de734daf4cc7b4e1ff318aaa875bdc0defca33907da34797d6e9e60708fb6_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/2d8d75a780a4e0d6cc2bc68812c93ea8120d858a2fa0d7a5e77aaebf77194839_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/a6df9490dcee4394bd2bbb8213b2f55aac5481048c8e9a7c0dafe7c212c887f6_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/1bdf02222f0a79e5f5e2e7bf171373b9d839ec9169177d184eeec8dab7ae4e8a_sk
        # 2 orgs 2 peers
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/d2fb3f7b9dd9c85640942340f4922840718c986c780658aa689807ab2f7a8e89_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/10d6775a4f32fe538407123fb5a0a41899de2bc6af11fbb11c33293d3a8ac908_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/d926e3d5368a08bc7433a872e48a67b3f72add955bcd0fdddd6ae6dfd6365ea2_sk
        #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/a5d43859dca598cd90fed67728bb7ae44c6f487ce2a66cbf30bd016589ae44de_sk
        path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/cba5e88ceaf8060413fdaf9e4edd2c3127a8fa83ff63068c56c9949cfba85a7c_sk
      clientSignedCert:
        path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/cert.pem
channels:
  mychannel:
    created: true
    orderers:
    - orderer.example.com
    - orderer2.example.com
    - orderer3.example.com
    peers:
      peer0.org1.example.com:
        eventSource: true
      peer0.org2.example.com:
        eventSource: true

    contracts:
    #- id: fabcargo
    #- id: fabcarjs
    - id: chitfundjs
      version: "1"
      #language: golang    #contract language must be one of [golang, node, java]
      language: node



organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      #- peer1.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
    adminPrivateKey:
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/4bf74df2307c82693817f3128673ce8cf21580f8e21771ae9ba814d62f2b914f_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/d5bb3c4ba19cdf495a7ed71a225eac258cb7779b659d6731d62aa672400eddc9_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/c21e73a41e30392467a66866cdaad0465e2d8927b473d798f35c43b73b577da9_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/49ff1975b7a0c148252bed40b9d0259122411e598189696bac5ed195f0812259_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/6d30f5301cc2547a2c4178ec133fe0720c86c2c82e7dbacd5d60a2494aeb85f4_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/046beef62c72582927fb64f07489cc0d37b082591d5977e7392683d93f7a4a07_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/e37d9e4c43309d0943876be41812002dcb302c27f3e0eb25e13a3b6ae0f47d27_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/f910b71d04b111cd69a5716e9ec2f68fe9aa2f60e5763b41642cef561ddc636a_sk
      # 2 org 4 peers
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/ae12667ba4f267b108787e4246f121504e66c39c49a25d724a10de2dfebcb43a_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/1cb8220ba5a63c31441b05f1a285914a02f98c850971a17d635d30aed2166b01_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/5040f51342990083a275041a6aef08eff8c5b3aa2535e7582cbfc233b68eb01d_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/c7805248decf2eb155d9ebd61fc5e209b6a387df5e93cb61987ead56e84876d6_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/efc77634fb0b6d0bd50075cf1b9037554236ce4c46a6496521c164504f81b280_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/83fee661cc03d788483e9540ab8f28de626b7a12602776cf387a41026d0fa472_sk
      # 2 orgs 2 peers
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/90057e3f56f23e2738c8a2d9726f977689a6b405908e943c21318abc8dd61a8e_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/844bdd869246b05783c5e0219370b5344dab7e4631aae610202874c854695244_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/db5248027b3a6c08ad8a77b51e0ad3a5343a48fc9d68dec3b9b2bac011777cd3_sk
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/2d6a6dfb728359968b8be85a34fcd56bc0af412a615ed6b8d2098dc3fcf3d901_sk
      path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/9bf2d584b9e874ff6181c8a16f90faf173c400fe95483d0a8c872d268d8e92c1_sk
    signedCert:
      path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      #- peer1.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
    adminPrivateKey:
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/7d58b783ad80d9b051d35ab2e1fafa0533f860b23107e99f958f9bf376d0bb71_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/d9071d43f3725c67a69a837d2879e370d87ae3f809a528a4aefbd3824832efa2_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/d9071d43f3725c67a69a837d2879e370d87ae3f809a528a4aefbd3824832efa2_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/f66fa3af6870e728fcaab81ea919425eb771153e88d6b74457bbe6b8b3772825_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/2097f5acdba4394e7e24db4d670e7339ec200996781e93346dc29603ab8c4c94_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/a8bfeaf9e6f878101f074a500d787f3c8891b13dde9a96f447ee34cf35553c8a_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/73cfb46db5d034c8ac294a113c9269a1c5afbaaf549cb7518a4e50634da9519c_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/e6d5e9045abb8efff7e18e7a040da732a1017a9194bafbba137f5a00c0e179d0_sk
      # 2 orgs 4 peers
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/b0b32fb82ceffa87286a66c7f58211c476ff290cec528f477214a6b835ea331f_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/4d36cdd042014db5aaccddf5e87c52cd61ff203bdacbf238172bf3ad37f14b61_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/968def969daed93799ca2895f844b4a7c701e9b95fe4ac4c53ab28afc72076fc_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/eaf8976c7803d1cc53df0b80534429e6aff717ce958187fd2a89e06be2635da1_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/4a43c69d9dfa2dcb28e56ed5e7920ea00c82b10a37992f4b9cf793427d51fc99_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/501b8301649dcd676c58ca12fe40919a37b441563fcad25206c4dba3956f2cbf_sk
      # 2 orgs 2 peers
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/6476874f93b2bf8f0a1e9bb2a48d19e6ab311768337d47d9cab437b9b6f584e0_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/60eae4c63a14c6fc4a2398642d8bdc94d8e6fc04f206974300e38cf597479944_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/ad2672275fea94e0ff177121f4dbf8e7a0bfb92293c3d13cc1592ad306a3807e_sk
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/67003b88a1e48ccd2757efa8effafe066beac2579ace7619b3eaece5a1a1fa4c_sk
      path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/1a36a6b9e9ff1047eda172dde205386323028438bcace055a0e68b332949bd2c_sk
    signedCert:
      path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: ../orderer/crypto-config-ca/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer2.example.com:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
    tlsCACerts:
      path: ../orderer/crypto-config-ca/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem 
  orderer3.example.com:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer3.example.com
    tlsCACerts:
      path: ../orderer/crypto-config-ca/ordererOrganizations/example.com/orderers/orderer3.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/tlscacerts/tls-localhost-7054-ca-org1-example-com.pem

  #peer1.org1.example.com:
    #url: grpcs://localhost:8051
    #grpcOptions:
      #ssl-target-name-override: peer1.org1.example.com
      #grpc.keepalive_time_ms: 600000
    #tlsCACerts:
      #path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/tlscacerts/tls-localhost-7054-ca-org1-example-com.pem

  peer0.org2.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/tlscacerts/tls-localhost-8054-ca-org2-example-com.pem
  #peer1.org2.example.com:
    #url: grpcs://localhost:10051
    #grpcOptions:
      #ssl-target-name-override: peer1.org2.example.com
      #grpc.keepalive_time_ms: 600000
    #tlsCACerts:
      #path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/tlscacerts/tls-localhost-8054-ca-org2-example-com.pem 

certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../org1/crypto-config-ca/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org2.example.com:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../org2/crypto-config-ca/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
